// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRV9SswFBIb0bCRa6Q_ltigFQJrwjE8H4',
    appId: '1:957648416581:web:4eb1961ae54bd29833582c',
    messagingSenderId: '957648416581',
    projectId: 'insurancesync-3ca01',
    authDomain: 'insurancesync-3ca01.firebaseapp.com',
    storageBucket: 'insurancesync-3ca01.firebasestorage.app',
    measurementId: 'G-QL730CMMWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz7gNjRjyXOuqcyuhGmwYAlGiiidVF3Q8',
    appId: '1:957648416581:android:8753fed0b276d57e33582c',
    messagingSenderId: '957648416581',
    projectId: 'insurancesync-3ca01',
    storageBucket: 'insurancesync-3ca01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABxI6Lrw2vpeWJxUSQQ61kMtJU6HtQing',
    appId: '1:957648416581:ios:deeed5325e9bf17733582c',
    messagingSenderId: '957648416581',
    projectId: 'insurancesync-3ca01',
    storageBucket: 'insurancesync-3ca01.firebasestorage.app',
    iosBundleId: 'com.example.videoScreen',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABxI6Lrw2vpeWJxUSQQ61kMtJU6HtQing',
    appId: '1:957648416581:ios:deeed5325e9bf17733582c',
    messagingSenderId: '957648416581',
    projectId: 'insurancesync-3ca01',
    storageBucket: 'insurancesync-3ca01.firebasestorage.app',
    iosBundleId: 'com.example.videoScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRV9SswFBIb0bCRa6Q_ltigFQJrwjE8H4',
    appId: '1:957648416581:web:51588960f5b5602c33582c',
    messagingSenderId: '957648416581',
    projectId: 'insurancesync-3ca01',
    authDomain: 'insurancesync-3ca01.firebaseapp.com',
    storageBucket: 'insurancesync-3ca01.firebasestorage.app',
    measurementId: 'G-5XJPV5L1MM',
  );
}
